---
driver:
  network:
  - ["private_network", {ip: "192.168.33.42"}]
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[df_box_django::default]
    attributes:
